# Generated by Django 5.0.1 on 2024-01-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='investimentos',
        ),
        migrations.AddField(
            model_name='curso',
            name='investimento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
